version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: ${DB_login}
      POSTGRES_PASSWORD: ${DB_pass}
    ports:
      - "5432:5432"
    restart: unless-stopped