spring:
  liquibase:
    enabled: false
  datasource:
      url: # Указать ссылку на источник данных.
      username: # Указать имя пользователя СУБД
      password: # Указать пароль пользователя СУБД
      driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

