spring:
  liquibase:
    enabled: true
  datasource:
      url: jdbc:postgresql://localhost:5432/mediacontent
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: validate

