server:
  #  servlet:
  #    context-path: /yur-project
  port: 8080
spring:
  #  application:
  #    name: yur-project
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: #url
    username: #username
    password: #password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create-drop